basePath: /api/v1
definitions:
  models.Organization:
    description: Organization information
    properties:
      key:
        minLength: 4
        type: string
      name:
        minLength: 4
        type: string
      org_id:
        type: integer
    required:
    - key
    - name
    type: object
  models.OrganizationRequest:
    properties:
      key:
        minLength: 4
        type: string
      name:
        minLength: 4
        type: string
    required:
    - key
    - name
    type: object
  models.OrganizationUpdateRequest:
    properties:
      name:
        minLength: 4
        type: string
    required:
    - name
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cronuseo API
  version: "1.0"
paths:
  /organization:
    get:
      description: Get all organizations.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Organization'
            type: array
        "500":
          description: Internal Server Error
      tags:
      - Organization
    post:
      consumes:
      - application/json
      description: Create organization.
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.OrganizationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Organization'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      tags:
      - Organization
  /organization/{org_id}:
    delete:
      description: Delete organization.
      parameters:
      - description: Organization ID
        in: path
        name: org_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Organization
    get:
      description: Get organization by ID.
      parameters:
      - description: Organization ID
        in: path
        name: org_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Organization'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Organization
    put:
      consumes:
      - application/json
      description: Update organization.
      parameters:
      - description: Organization ID
        in: path
        name: org_id
        required: true
        type: integer
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.OrganizationUpdateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Organization'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      tags:
      - Organization
swagger: "2.0"
