FROM golang:1.19.1-alpine3.16

COPY . /api
WORKDIR /api
EXPOSE 8080 4000
RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest
RUN go mod download
RUN cd cmd/server && CGO_ENABLED=0 go build -gcflags "all=-N -l" -o ./../../
ENV GO111MODULE=off
RUN pwd && ls
CMD [ "/go/bin/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "./server" ]