version: '3.8'
services:
  api:
    image: ghcr.io/shashimalcse/cronuseo
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - APP_ENV=local
volumes:
  api:
  database_postgres:     
  cache:
    driver: local   
