version: '3.8'
services:
  mgt_api:
    container_name: cronuseo
    image: ghcr.io/shashimalcse/cronuseo
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - APP_ENV=local
