version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    volumes: 
      - data:/var/lib/postgressql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - "api.network"  
  api:
    build: .
    ports:
      - "8080"
    networks:
      - "api.network"  
    deploy:
        replicas: 2
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "api"
    networks:
      - "api.network"  

volumes:
  data:

networks:
  api.network:
    