version: '3.8'
services:
  cronuseo-db:
    image: postgres
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./data/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 

  keto-db:
    image: postgres
    restart: always
    ports:
      - "${KETO_DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${KETO_DB_USERNAME}
      - POSTGRES_PASSWORD=${KETO_DB_PASSWORD}
      - POSTGRES_DB=${KETO_DB_NAME}
      - DATABASE_HOST=${KETO_DB_HOST} 
  keto:
    image: oryd/keto:v0.10.0-alpha.0
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    depends_on:
      - keto-db
  keto-migrate:
    image: oryd/keto:v0.10.0-alpha.0
    links:
      - keto-db:keto-db
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://keto:keto@keto-db:5432/keto?sslmode=disable
    command: ["migrate", "up", "-y"]
    restart: on-failure
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cronuseo-db

volumes:
  api:
  database_postgres:        
