version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: cronuseo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db