version: v0.10.0-alpha.0

log:
  level: debug

namespaces:
  - id: 0
    name: permission 
serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: postgres://keto-db:5432/keto?sslmode=disable&user=keto&password=keto