jwks: "https://api.asgardeo.io/t/cronuseo/oauth2/jwks"
mgt_api: ":8080"
check_api: ":8081"
check_grpc: ":50051"
mongo: "mongodb://mongodb:27017"
mongouser: "root"
mongopassword: "rootpassword"
default_org: "super"
mongodbname: "cronuseo"
rbac_policy: "./policy/policy.rego"
mongo_org_coll_name: "organizations"
