dsn: "postgres://localhost:5432/cronuseo?sslmode=disable&user=postgres&password=postgres"
jwks: "https://api.asgardeo.io/t/shashimal/oauth2/jwks"
keto_read: "localhost:4466"
keto_write: "localhost:4467"
api: "localhost:8082"
redis_endpoint: "localhost:6379"
redis_password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
mongo: "mongodb://localhost:27017"
mongouser: "root"
mongopassword: "rootpassword"
default_org: "super"