dsn: "postgres://cronuseo-db:5432/cronuseo?sslmode=disable&user=postgres&password=postgres"
jwks: "https://api.asgardeo.io/t/shashimal/oauth2/jwks"
keto_read: "keto:4466"
keto_write: "keto:4467"
api: "api:8080"

organization:
  config:
    username: admin
    password: admin
    organization: "super"