endpoint:
  management : ":8080"
  check_rest : ":8081"
  check_grpc : ":50051"
auth:
  jwks: "https://api.asgardeo.io/t/cronuseo/oauth2/jwks"
database:
  url : "mongodb+srv://shashimalcse:tltPm2YhaUlAmNGz@cluster0.5klckrk.mongodb.net/"
  name : "cronuseo"
  user: "shashimalcse"
  password: "tltPm2YhaUlAmNGz"
root_organization:
  name : "super"
opa:
  rbac: "/Users/thilinashashimal/Desktop/Cronuseo/policy/policy.rego"

