jwks: "https://api.asgardeo.io/t/cronuseo/oauth2/jwks"
mgt_api: "mgt_api:8080"
check_api: "check_api:8081"
mongo: "mongodb://localhost:27017"
mongouser: "root"
mongopassword: "rootpassword"
default_org: "super"
mongodbname: "cronuseo"
rbac_policy: "./policy/policy.rego"
MongoOrgCollName: "organizations"