jwks: "https://api.asgardeo.io/t/cronuseo/oauth2/jwks"
mgt_api: ":8080"
check_api: ":8081"
mongo: "mongodb+srv://cronuseo:hMRqhU4pzdYtZM5J@cluster0.7jo2zkm.mongodb.net/"
mongouser: "cronuseo"
mongopassword: "hMRqhU4pzdYtZM5J"
default_org: "super"
mongodbname: "cronuseo"
rbac_policy: "/Users/thilinashashimal/Desktop/Cronuseo/policy/policy.rego"
mongo_org_coll_name: "organizations"