jwks: "https://api.asgardeo.io/t/cronuseo/oauth2/jwks"
mgt_api: "localhost:8080"
check_api: "localhost:8081"
mongo: "mongodb://localhost:27017"
mongouser: "root"
mongopassword: "rootpassword"
default_org: "super"
mongodbname: "cronuseo"
rbac_policy: "/Users/thilinashashimal/Desktop/Cronuseo/policy/policy.rego"