jwks: "https://api.asgardeo.io/t/cronuseo/oauth2/jwks"
mgt_api: "localhost:8080"
check_api: "localhost:8081"
mongo: ""
mongouser: "cronuseo"
mongopassword: "0F1Cie7ugBFqCCp3"
default_org: "super"
mongodbname: "cronuseo"
rbac_policy: "/Users/thilinashashimal/Desktop/Cronuseo/policy/policy.rego"
mongo_org_coll_name: "organizations"