dsn: "postgres://db:5432/cronuseo?sslmode=disable&user=postgres&password=postgres"
jwks: "https://api.asgardeo.io/t/shashimal/oauth2/jwks"
keto_read: "keto:4466"
keto_write: "keto:4467"
api: "api:8080"
redis_endpoint: "cache:6379"
redis_password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
mongo: "mongodb://mongodb:27017"

organization:
  config:
    username: admin
    password: admin
    organization: super