jwks: "test"
mgt_api: "test"
check_api: "test"
mongo: "mongodb://localhost:27017"
mongouser: "root"
mongopassword: "rootpassword"
default_org: "super"
mongodbname: "cronuseo"
rbac_policy: "test"
mongo_org_coll_name: "organizations"